### ISSUE TITLE
TypeError: Inputmask is not a function in Node/Vue

### ISSUE THREAD

**Issue by ghost** [RobinHerbots/Inputmask#2387]
- Inputmask version
`^5.0.6-beta.12` or `^5.0.5`

- My code
```js
const Inputmask = require('inputmask')
const docField = document.querySelector('#doc-field')

Inputmask({
  mask: '999.999.999-99',
  showMaskOnHover: false
}).mask(docField)
```
- Describe the bug
`TypeError: Inputmask is not a function`

am i doing something wrong?
I used it before in the same way, but now it's just not working

**Comment by joeyw7** [comment]
try require('inputmask').default
or downgrade to 5.0.0, require('inputmask') would work on 5.0.0
whatever introduced must have changed the behaviours.

**Comment by adlerdias** [comment]
is there any particular reason to not use import?

```javascript
import Inputmask from 'inputmask';
```

**Comment by jackiems82** [comment]
I alos use it in a vue project and I needed to install @types/inputmask to make Typescript recognise it. That is the usual approach for a library that does not bring its own types.
