### ISSUE TITLE
InputMask.extendAliases is not a function type error after updating to 5.0.5

### ISSUE THREAD

**Issue by abdelrhman-adel** [RobinHerbots/Inputmask#2371]
I'm using 5.0.5 
it was working properly before with 5.0.3 
i'm using typescript in an angular project
when I try 
```
import * as Inputmask from 'inputmask';
import { aliases } from './input-mask-aliases';
Inputmask.extendAliases(aliases);
```
I get 
`TypeError: Inputmask.extendAliases is not a function`

rolling back to 5.0.3 solves the issue

**Comment by RobinHerbots** [comment]
@RobinHerbots, 

Try
```
import Inputmask from 'inputmask';
import { aliases } from './input-mask-aliases';
Inputmask.extendAliases(aliases);
```
