### ISSUE TITLE
script does not work

### ISSUE THREAD

**Issue by ShurikEv** [RobinHerbots/Inputmask#2241]
- I want resolve my problem: after update plugin with version 3.x to 5.0 in my mask unlimited symbol
settings:
```
'alias': 'integer', 
'groupSeparator': ' ', 
'allowMinus': false, 
'autoGroup': true, 
'integerDigits':9, 
'autoUnmask':true
```

I can input unlimited digits greater then 9

I try do it on jsfiddle.net, but script does not work: 

> TypeError: $(...).inputmask is not a function

- https://jsfiddle.net/ehfbad9j/1/
- OS: Win10
- Browser: Mozzila
- Inputmask version: 5.0

**Comment by RobinHerbots** [comment]
@ShurikEv , 

Here is a working example.

https://jsfiddle.net/ydmchx40/1/

The numeric alias is totally rewritten and some options are changed.  See readme for numerics.
The integerdigits option is removed.  Yu can set a max value instead.

**Comment by ShurikEv** [comment]
Thanks for your reply.
'alias': 'integer' - also its removed?

**Comment by RobinHerbots** [comment]
@ShurikEv , 

No alias integer is still present.

**Comment by ShurikEv** [comment]
Thanks again :-)

I have a max=999999,99. I can input both 12345.67 or 12345.6 or 12345. 

1. After apply the mask if value was 12345.6 it masked to 12 345.60 and 12345 -> 12345.00. How to remove extra zeros? 12345.6 -> 12 345.6 and 12345 -> 12 345
Example: https://jsfiddle.net/adm13pvy/

2. How to avoid resetting to the maximum value when entering extra characters? The plugin should not be allowed to enter extra characters
Example: mask=999.99, I input 123  then I press 4 and value is equal 999.99. Value should stay 123

**Comment by RobinHerbots** [comment]
@ShurikEv , 

I changed the behavior in 5.0.1-beta.4

**Comment by RobinHerbots** [comment]
@ShurikEv , 

So point 2 should be solved.  For point 1 this is only when setting the value, not while typing.
I will also change that behavior.

**Comment by RobinHerbots** [comment]
@ShurikEv , 

Version 5.0.1-beta.5 also solves point 1.

https://jsfiddle.net/tbj12hm7/1/

**Comment by ShurikEv** [comment]
Thanks!
