### ISSUE TITLE
ERROR TypeError: inputmask__WEBPACK_IMPORTED_MODULE_3__ is not a function

### ISSUE THREAD

**Issue by tomasziwaszko** [RobinHerbots/Inputmask#2437]
After updating to 5.0.5 version I get this error:
`ERROR TypeError: inputmask__WEBPACK_IMPORTED_MODULE_3__ is not a function`
in that line:
`Inputmask(mask, { skipOptionalPartCharacter: '' }).mask(this.el.nativeElement);`

It worked correctly with version 5.0.1

Why I get this error now?
I use inputmask in Angular so I am also using:
`@types/inputmask": "4.0.2"`

and I import mask in a following way:
`import * as Inputmask from 'inputmask';`

**Comment by tomasziwaszko** [comment]
ok problem solved. I ridded of `@types/inputmask` and I use var declaration instead of module import

`declare var Inputmask: any;`
