### ISSUE TITLE
3.2.0 Error extendDefinitions and extendAliases not functions

### ISSUE THREAD

**Issue by newenegue** [RobinHerbots/Inputmask#1024]
I've just tried the new `3.2.0` release and I'm getting the following errors when initializing the `jquery.inputmask.bundle.js` file.  I haven't changed any of my projects code since switching from `3.1.63` to `3.2.0`.  It was previously working perfectly on `3.1.63`.

`jquery.inputmask.bundle.js:1943 Uncaught TypeError: Inputmask.extendDefinitions is not a function`
`jquery.inputmask.bundle.js:2050 Uncaught TypeError: Inputmask.extendAliases is not a function`

**Comment by RobinHerbots** [comment]
How exactly do you use the bundle?  I mean just a script tag or a module loader?

**Comment by newenegue** [comment]
@RobinHerbots I'm using a combination of bower and require.js to include the bundle.  My project is built on sails.js and it injects the bundle into a script tag given the relative path to the file.  I'll try manually including the script tag to see if that makes any difference.

**Comment by RobinHerbots** [comment]
I will commit a patch for it tomorrow.  The recommended way when using via
requirejs is by including the separate files. (include only what is
required)  Anyway, it should also work when using the bundle.

Op di 8 sep. 2015 om 20:25 schreef Eugene notifications@github.com:

**Comment by newenegue** [comment]
@RobinHerbots thanks!

**Comment by RobinHerbots** [comment]
@newenegue , 

Have you tried requiring only the files you need?  I'm thinking of removing the bundle all together

**Comment by newenegue** [comment]
@RobinHerbots Through require.js I had to include `dependencyLib`, `inputmask`, `jquery.inputmask`, `inputmask.extensions` and `inputmask.phone.extensions`.  I didn't realize I had to include `dependencyLib` as it wasn't clear in the usage instructions.   The instructions made it seem like I only needed `inputmask.js` and `jquery.inputmask.js` at a minimum.

Additionally, when I try to use the `phone` or `phonebe` alias I'll get an error that `phone-codes/phone-codes.js` cannot be found.  I do see that the bower correctly puts the phone code files into `/extra/phone-codes`.  Should I be including the phone code files in require.js as well?

**Comment by newenegue** [comment]
@RobinHerbots Actually I see from the phone extension doc that I can assign the url when initializing the inputmask.  

Everything seems to be working well when I include the files individually

**Comment by RobinHerbots** [comment]
@newenegue , 

Ok I need to update the documentation.  The dependencyLib is new and still a WIP. It will enable to use another framework (or just vanilla javascript) instead of jquery.

Yes for the phone mask to work you need to specify the correct url in the options.

**Comment by SomethingSexy** [comment]
Can you make dependencyLib relative to inputmask? So something like "./dependencyLib".  For AMD/RequireJS users we should be able to just setup inputmask as a path and then we don't need to create another path definition for dependencyLib.

**Comment by RobinHerbots** [comment]
@SomethingSexy , 

The idea is to pick the dependencyLib you prefer.  See the WIP in the js folder.

**Comment by SomethingSexy** [comment]
@RobinHerbots Ya, I gotcha.  Is it possible to at least namespace it then or name it something more specific to your plugin?

**Comment by RobinHerbots** [comment]
@SomethingSexy ,

Yep I will do that.
